app:
  httpAddr: ":8080"

ondcConfigs:
  buyerAppUrl: "https://ondc-buyer-staging-app.yash.com"
  buyerAppUri: "/"
  gatewayUrl: "https://staging.gateway.proteantech.in"
  signingPrivateKey: "o/Wck3/V7upUtvUi7HOk2L2ut+GbtgGbKYYEFFwhKQgzwsfjS8QkH9CIYJotv3s/kBqIITtYWopUEZ7xC3CyvQ=="
  signingPublicKey: "M8LH40vEJB/QiGCaLb97P5AaiCE7WFqKVBGe8Qtwsr0="
  ondcEncryptionPublicKey: "MCowBQYDK2VuAyEAduMuZgmtpjdCuxv+Nc49K0cB6tL/Dj3HZetvVN7ZekM="
  privateKeyCrypto: "MC4CAQAwBQYDK2VuBCIEIAClC7O6wyl6IfCqkPjEk2NGXVUbqgT54vVSAzBL/hhW"
  publicKeyCrypto: "MCowBQYDK2VuAyEAtexpJPC5LYuGHgbRuyZkiIRTUvoAaTzsAh3rbaWPrz8="
  registryUrl: "https://staging.registry.ondc.org"
  gstLegalEntityName: "FT PRIVATE LIMITED"
  gstBusinessAddress: "1st Floor, T Tower,  KM Compound, Mumbai 013."
  gstNo: "06AAHCP1178L1Z4"
  entityGstCityCode: "std:080"
  nameAsPerPan: "FT PRIVATE LIMITED"
  panNo: "AAHCP1178L"
  panDateOfIncorporation: "05/01/2022"
  nameOfAuthorisedSignatory: "NSSS"
  addressOfAuthorisedSignatory: "LP"
  emailId: "yash.bansal@demo.com"
  mobileNo: "7792013965"
  country: "IND"
  subscriberId: "ondc-buyer-staging-app.yash.com"
  validFrom: "2023-12-12T18:27:54.101Z"
  validUntil: "2030-07-08T06:27:54.101Z"
  networkParticipantDomain: "ONDC:TRV11"
  networkParticipantType: "buyerApp"
  subscribeUniqueId: "67baa06d-f90a-486c-85e5-cc621b743f08"
  requestId: "67baa06d-f90a-486c-85e5-cc621b743f46"